### ISSUE TITLE
Cannot run jsx

### ISSUE THREAD

**Issue by subpublic** [mhart/react-server-routing-example#2]
Hello

running <code>node server.js</code>
gives a error

<pre>../react/react-server-example-master/App.js:50
    return (< div >
            ^
SyntaxError: Unexpected token <
</pre>

(There's actually not space between the div)

I'm running node v0.12.2

**Comment by subpublic** [comment]
Sorry, pulled home the latest version. Now it works!

**Comment by daslicht** [comment]
Do you like to post an existing example using jsx please?
