### ISSUE TITLE
How come react 16.4.2 made server side routing so complicated

### ISSUE THREAD

**Issue by jonnydungeons** [mhart/react-server-routing-example#5]
Hi Michael,
I just started using react 16.4.2 from 15.5.4 and I have to say that server side routing was so much less complicated. I easily served my html using a hapijs server and basically had to make sure I disabled hash routing on the client. On the hapijs side I had to make sure my routes served up the html so I had a pretty simple FileHandler() function to do this and mapped all my static routes to it. Then as I built out my pages on the client I still needed to create a route in the react router but difference is that now I needed to make sure the same route also existed on the hapijs server. Jeez. Kudos for coming up with this solution using browserfy but your solution does not look like it is for the faint of heart. Do you know if there is a solution using reactjs 16.4.2 that is more like what I describe?

-J0

**Comment by mhart** [comment]
Sorry, I don't, no – probably better to ask on a React forum or similar?
